### ISSUE TITLE
🐛: Punch: 3D echo CORS issue

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#1006]
https://webserver-fusion-project-portal-prod.radix.equinor.com/apps/punch/c5365fa9-b6da-4ca3-bebb-d783a63ae467?tab=grid&item=3782351

![image](https://github.com/equinor/cc-components/assets/89254170/fa5d0168-a048-4adc-8994-3fda9de46661)

![image](https://github.com/equinor/cc-components/assets/89254170/a5ec11f5-78ec-4417-adbd-f7aa2cd68443)

**Comment by kjellhaaland** [comment]
@Gustav-Eikaas this issue still persist when using the 3D viewer through https://webserver-fusion-project-portal-prod.radix.equinor.com and not https://project.fusion.equinor.com.
The Echo team has specifically whitelisted our domains, so if we have users that uses the webserver-url, we should probably ask them to whitelist that domain as well.

@Gustav-Eikaas any thoughts?

**Comment by ken-mellem** [comment]
won't fix ref comment above.
