### ISSUE TITLE
🐛[ENQ6886212]: Punch: Bookmarks issues 

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#1017]
## Description
Multiple users claiming the bookmarks does not work in our Workspace PowerBi component.
This issue should be resolved as numerous users claim it does not work. I think the best way to solve this is to spend some time rally testing bookmarks and trying to find a reliable repro.

## Reproduce
Unknown, user says "Sometimes it works, sometimes it does not"
Ticker number: ENQ6886212

## Dev context
We have very little control over how the bookmarks works in PowerBi. It's the embedded component that takes a B64 payload and sets the necessary state. 

- What happens if the report changes
- What happens if we upgrade a major version of the embed
- How can we possibly detect and handle this

## Bookmark info

PowerBi bookmarks are JSON structures compressed using gzip. One bookmark with some simple filters is roughly 3500 lines of prettified JSON and 108Kb.

They store some interesting data such as:

- ActiveSection (name of current section)
- Dim_ProjectMaster filter (if context report)
- Id's of specific visuals e.g 2505a7f846848d0a792c
- Property names like e.g (Status) (punch.status)

This means that any change to the report that affects these fields will potentially cause bookmarks to break.

**Comment by ken-mellem** [comment]
Agreed to close.
