### ISSUE TITLE
🐛: Handover: 3D shows tag-lifecycle-status, must show mcStatus

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#1022]
## Description
Status shown in 3D tab is "Reserved", "Planned", "As-Built" instead of "OS","PA","PB","OK"

## Reproduce
![image](https://github.com/equinor/cc-components/assets/11732817/f2e1e3ab-3998-409c-ba9e-ce7093ba5d36)

## Expected behavior
Shows mcStatus (like in WO 3D)

**Comment by atlewee** [comment]
It seems like there is fundamental issues visualizing commPk in 3D
( Echo can only highlight tags, and line tags often cross commPks and must be partly colored by pipetest status )
There is also no mapping between pipetest and 3D available making this impossible on todays data model.
In addition, all dummyTags such as pipetest/loop, Cables and HT cables, does not exist in 3D

Since we can not visualise commPk in 3D with todays data model we should disable the 3D tab on commPk for now.

**Comment by ken-mellem** [comment]
@Gustav-Eikaas att ADR - this is some-kind of decision or rather technical limitation which we definitely should document, in order not to re-attempt to re-introduce this functionality again later.

**Comment by Gustav-Eikaas** [comment]
Made a PR in lighthouse, trying to document this as a failed experiement. 

- [ ] equinor/lighthouse#603
