### ISSUE TITLE
🐛: Workorder : Code not minified?

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#1026]
## Description
![image](https://github.com/equinor/cc-components/assets/89254170/7e6c8649-36e5-493e-8b5f-e444b222616c)
React devtools extension complaining that this app ships both a production and a development build of react. Seems to only be workorder that does this. Unsure why. Needs investigating🔎

## Reproduce
1. Install the react devtools chromium extension
2. Load workorder application in production.
3. The extension turns red and a warning is issued when pressing it.

## Expected behavior
Extensions should not indicate that the development version of react is present in production.

  
**note**: This may be a bug in the extension caused by our single spa architecture. But if it is its weird how inconsistently consistent it is.

**Comment by ken-mellem** [comment]
Agreed to close
