### ISSUE TITLE
🎁: Handover: KPI row

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#1035]
## Expected outcome
Clear KPI's

## Business Value / Developer Experience
Yesterday a Commissioning manager asked me how the KPI numbers work and I could not answer, had to calculate and check the numbers before i understood how it works.

We need to make the KPI numbers more clear.
User did not understand it was two sections. (did not notice the sqare brackets)
![image](https://github.com/equinor/cc-components/assets/11732817/bcd83485-ace0-4f9c-9c26-b9e2030a22a3)

## Acceptance Criteria
- [x] Clear separation between RFC and RFO sections
- [ ] The sum of numbers in each section should be same as total commPk  
(Overdue must be moved to its own section, maybe all the way to the right)

**Comment by EdwardBrunton** [comment]
@atlewee I have moved the KPIs into two separate sections, but i dont understand how you want the Overdue to look. Do you want them both merged into a single number? The other changes are in prod

![image](https://github.com/user-attachments/assets/f121f7ea-fc94-4739-b1fd-1689b3b0ba97)

**Comment by EdwardBrunton** [comment]
Waiting for UX input

**Comment by JoneUE** [comment]
@EdwardBrunton remove overdue. and as Atle said the sum in RFC should be the same as the sum of KPI in RFO section. you could use the fields RFC_Stauts and RFO_Status to get the correct KPIs
