### ISSUE TITLE
✨: CC-app-usage report

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#1052]
## Expected outcome
Get the report out in test and prod.
Ensure the correct access control.
Set the correct refresh frequency 

## Business Value / Developer Experience
Get insight in the usage of CC-apps

## Acceptance Criteria
Should be out in test and prod

**Comment by JoneUE** [comment]
@ken-mellem Denne kan vel lukkes?

**Comment by ken-mellem** [comment]
yes - this is to be covered by Fusion admin usage app.
