### ISSUE TITLE
🦺 QA: Loop -  🚬 test

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#1059]
Verify the CC app **Loop**.

> [!NOTE] 
> PROD (FAM api/client) vs TEST (Self Service)

### Verify usability

- [ ] the app works!
  - [ ] view table
  - [ ] view garden
  - [ ] view analytics
- [ ] I can apply filters, and data gets filtered
- [ ] open element/sidesheet
  - [ ] view applicable tabs 
  - [ ] check links

### Consolidate and Verify data by comparing

- [ ] manually inspect fields
  - [ ] calculations
  - [ ] date formatting
- [ ] verify perceived performance

### Code Quality

- [ ] integration test coverage
  - [ ] apply latest conventions and test framework
- [ ] logging registers in AI

**Comment by Gustav-Eikaas** [comment]
Needs to also verify that the filter values in each filter group is the same between prod and test
See this issue for more info: https://github.com/equinor/fusion-fam-self-service/issues/166

**Comment by ken-mellem** [comment]
equinor/fusion-fam-self-service#166 indicates that it has been verified once before. See [test results](https://github.com/equinor/fusion-fam-self-service/issues/166#issuecomment-2208228042)

**Comment by ken-mellem** [comment]
#### Loop
Testing

<details>
<summary>Rally test details</summary>

(Minor) *Sidesheet Overview table not same order**

Prod: 
![image](https://github.com/user-attachments/assets/396baaea-f160-49ac-a457-78ffcf24e525)

Test: 
![image](https://github.com/user-attachments/assets/dbb4c055-6450-4461-a413-a364c6818631)

(Minor) Missing rounding rule for Man hours in Self Service
![image](https://github.com/user-attachments/assets/fccb410f-f284-4c27-99b7-1bfd03bce215)


</details>
