### ISSUE TITLE
MC Views

### ISSUE THREAD

**Issue by jaysencpp** [equinor/cc-components#11]
# MC Views (WIP)
The MC App needs to migrate from Fusion Dataproxy using ProCoSys Views to FAM Views. Below is a proposal for the different data the App will need to consume.

## MC main app
- [x] projectIdentifier
- [x] projectDescription
- [x]  mcPkgId
- [x] mcPkgNumber
- [x] commPkgNumber
- [x] commPkgNumber
- [x] commPkgStatus
- [x] description
- [x] remark
- [x] system
- [x] subsystem
- [x] area
- [x] discipline
- [x] disciplineDescription
- [x] mcStatus
- [x] tagVolume
- [x] priority
- [x] priority2
- [x] priority3
- [x] phase
- [x] responsible
- [x] finalPunchPlannedDate
- [x] finalPunchForecastDate
- [x] finalPunchActualDate
- [x] punchAcceptActualDate
- [x] rfccPlannedDate
- [x] rfccForecastDate
- [x] rfccActualDate
- [x] tacPlannedDate
- [x] tacForecastDate
- [x] rfocPlannedDate
- [x] rfocForecastDate
- [x] rfocActualDate
- [x] tacIsShipped
- [x] tacIsAccepted
- [x] rfocIsShipped
- [x] rfocIsRejected
- [x] rfccIsShipped
- [x] rfccIsRejected
- [x] rfccShippedDate

## MC/Workorders
- [x] workOrderNumber
- [x] workOrderId
- [x] description
- [x] projectProgress
- [x] workOrderStatus
- [x] materialStatus

## MC/NCR
- [ ] documentNumber
- [ ] documentId (?)
- [ ] title

## MC/Punch
- [x] tagNumber
- [x] status
- [x] description
- [x] toBeClearedBy
- [x] sorting
- [x] punchId?
- [x] tagId?

I need to be able to generate this URL: [...]/Completion#PunchList|23674669?itemId=3743342

**Comment by jaysencpp** [comment]
## Suggested change to MC/Workorder
See https://github.com/equinor/cc-components/issues/13#issuecomment-1276009664

**Comment by jaysencpp** [comment]
## Suggested changes to MC/Main app
Placeholder

**Comment by Gustav-Eikaas** [comment]
@espenkalle sync this issue to whatever you're working on

**Comment by Gustav-Eikaas** [comment]
@espenkalle
