### ISSUE TITLE
🎁: SWCR filter and column names

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#1115]
## Expected outcome

- [x] Project
- [x] Facility
- [x] SWCR Contract
- [x] SWCR Status
- [x] SWCR Supplier 
- [x] SWCR Functional System = System
- [x] SWCR Priority
- [x] SWCR Control System
- [x] SWCR Types
- [x] SWCR Node Identifier
- [x] SWCR Action
- [x] Next to Sign
- [x] Next To Sign Role
- [x] Last Signed By
- [x] Last SIgned By Role
- [x] Comm Priority 1
- [x] Comm Priority 2
- [x] Comm Priority 3
- [x] Comm System
- [x] Comm Phase
- [x] Comm Pkg
- [x] Handover Status

**Comment by aman-riaz** [comment]
new fields are now added in SWCR view @EdwardBrunton
