### ISSUE TITLE
🎁: All Hanging Gardens. Always display current week

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#1156]
## Expected outcome

Always display current week, even if there are no data points as in the picture below. This is a functionality in the old Hanging Garden

![Image](https://github.com/user-attachments/assets/db79b924-66a5-46e6-bb80-1cf465fe96c6)

**Comment by ken-mellem** [comment]
We should prioritize this, to have the same expected functionality for the new app.

**Comment by ken-mellem** [comment]
@kjellhaaland Jone says something with Pipetest? I have asked him for a comment.

**Comment by JoneUE** [comment]
Looks good on all apps, except Pipetest

**Comment by kjellhaaland** [comment]
Pipetest is now fixed.
Deploying to production.
