### ISSUE TITLE
⚙: Loop namings

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#1167]
## Expected outcome
Group by:
![Image](https://github.com/user-attachments/assets/724e2731-db67-4b74-8804-1cf653582eed)

- Responsible -> Form Responsible
- Loop Tag (remove)
- Priority -> Comm Priority 1
- Comm Priority 2
- Comm Priority 3
- Comm Pkg
- System
- MC Pkg
- RFCC (C01)
- RFOC (C07)

Sidesheet
![Image](https://github.com/user-attachments/assets/833c225e-4215-4469-bb28-752c7599479e)

- System
- Project
- Tag Area
- Tag Status
- MC status of content
- Planned MC complete of content
- Actual MC complete of content
- Comm Priority 1
- Comm Priority 2
- Comm Priority 3

Rename Tag Location to Tag Area in filters and table

**Comment by ken-mellem** [comment]
@kjellhaaland can we merge this now?
