### ISSUE TITLE
SWCR Views

### ISSUE THREAD

**Issue by jaysencpp** [equinor/cc-components#12]
# SWCR Views (WIP)
The SWCR App needs to migrate from Fusion Dataproxy using ProCoSys Views to FAM Views. Below is a proposal for the different data the App will need to consume.

## SWCR main app
- [x] projectIdentifier
- [x] projectDescription
- [x]  swcrNo
- [x] swcrId
- [x] title
- [x] description
- [x] modification
- [x] priority
- [x] system
- [x] controlSystem
- [x] contract
- [x] action
- [x] supplier
- [x] node
- [x] status
- [x] referenceTypes
- [x] types
- [x] createdAtDate
- [x] dueAtDate
- [x] nextToSign
- [x] nextsToSign
- [x] nextSignRanking
- [x] estimatedManhours
- [ ] cntAttachments
- [x] cpkgNo
- [x] cpkgPhase
- [x] cpkgStartPlannedAtDate
- [x] cpkgStartForecastAtDate
- [x] cpkgFinishPlannedAtDate
- [x] cpkgFinishForecastAtDate
- [x] latestSignRanking

## SWCR/Signatures
- [x] swcrNo
- [x] ranking
- [x] signatureRole
- [x] functionalRole
- [x] person
- [x] signDate
- [x] signStatus
- [x] swcrId

**Comment by jaysencpp** [comment]
## Suggested changes to SWCR
Placeholder

**Comment by ken-mellem** [comment]
@espenkalle fyi
