### ISSUE TITLE
Handover Views

### ISSUE THREAD

**Issue by jaysencpp** [equinor/cc-components#13]
# Handover Views (WIP)
The Handover App needs to migrate from Fusion Dataproxy using ProCoSys Views to FAM Views. Below is a proposal for the different data the App will need to consume.

## Handover main app
- [x] projectIdentifier
- [x] projectDescription
- [x]  commpkgNo
- [x] commpkgId
- [x] system
- [x] progress
- [x] area
- [x] commpkgStatus
- [x] mcStatus
- [x] priority1
- [x] priority2
- [x] priority3
- [x] plannedStartDate
- [x] actualStartDate
- [x] plannedFinishDate
- [x] ActualFinishDate
- [x] phase
- [x] responsible
- [x] hasUnsignedActions
- [x] forecastFinishDate
- [x] volume
- [x] forecastTacDate
- [x] mcPkgsCount
- [x] mcPkgsRFCCShippedCount
- [x] mcPkgsRFCCSigned
- [x] mcPkgsRFOCShipped
- [x] mcPkgsRFOCSigned
- [x] tacIsAccepted
- [x] tacIsShipped
- [x] tacIsRejected
- [x] plannedTacDate
- [x] forecastStartDate
- [x] mcDisciplineCodes
- [x] mcDisciplines
- [x] IsDemolition
- [x] demolitionPlannedStartDate
- [x] demolitionForecastStartDate
- [x] demolitionActualStartDate
- [x] demolitionPlannedFinishDate
- [x] demolitionForecastFinishDate
- [x] demolitionActualFinishDate
- [x] remark
- [x] rfocIsShipped
- [x] rfocIsRejected
- [x] rfccIsShipped
- [x] rfccIsAccepted
- [x] rfccIsRejected
- [x] demolitionDCCAcceptedDate
- [x] demolitionRFRCShippedDate
- [x] tacIsActualDate
- [x] rfccShippedDate
- [x] rfocPlannedDate
- [x] rfocForecastDate
- [x] rfocActualDate
- [x] rfocShippedDate

## Handover/Details
- [ ] nextToSign

## Handover/MCPackages
- [x] commpkgId
- [x] mcPkgNo
- [x] mcPkgId 
- [x] mcStatus 
- [x] rfccShippedActualDate 
- [x] rfccIsAccepted
- [x] rfccIsRejected
- [x] rfccIsShipped
- [x] rfocIsAccepted 
- [x] rfocIsRejected
- [x] rfocIsShipped

## Handover/NCR
- [ ] documentNumber
- [ ] documentId (?)
- [ ] title

## Handover/Workorders
- [x] workOrderNumber
- [x] workOrderId
- [x] description
- [x] projectProgress
- [x] workOrderStatus
- [x] materialStatus

## Handover/Unsigned Tasks
- [x] taskNumber
- [x] title
- [x] documentId?
- [x] taskId?

I need to be able to generate this URL: [...]/Documents/Document#id=114212839&content=TASK!aa7e60c4-2d6d-424a-a83d-6a2ee8f209d9&tab=content

## Handover/Unsigned Actions
- [x] actionNumber
- [x] title
- [x] description 
- [x] commPkgId
- [x] actionId?

I need to be able to generate this URL: [...]/Completion#CommPkg|112647990?bf=1&content=MAINACTION!2fc767f3-7421-15e3-3a66-316e2d3a21fc

## Handover/Punch
- [x] tagNumber
- [x] status
- [x] description
- [x] toBeClearedBy
- [x] sorting
- [x] punchId?
- [x] tagId?

I need to be able to generate this URL: [...]/Completion#PunchList|23674669?itemId=3743342

## Handover/SWCR
- [x] swcrNumber
- [x] status
- [x] description
- [x] priority
- [x] swcrId

## Handover/Query
- [x] queryNumber
- [x] queryId?
- [x] title
- [x] status
- [x] nextToSign
- [x] type

I need to be able to generate this URL: [...]/Documents/Document/#id=114890226

## New fields that have been requested and not yet implemented in current solution
- [x] open PA
- [x] open PB
- [x] not signed MCCRs 
- [ ] open work orders (< 100%)
- [x] not signed CPCLs
- [ ] open SWCRs 
- [ ] not signed tasks
- [ ] not signed actions
- [ ] open queries
- [ ] remaining mhrs on open work orders

New Issues is requested to deal with these.
- [ ] #383

**Comment by jaysencpp** [comment]
## Suggested changes to Handover/MCPackages
At the moment we need to resolve each MC packages' RFOC and RFCC status based on the fields
* rfccIsAccepted -> "RFCC Accepted"
* rfccIsRejected -> "RFCC Rejected"
* rfccIsShipped -> "RFCC Sent" 
If none of the above -> "OS"

* rfocIsAccepted -> "RFOC Accepted"
* rfocIsRejected -> "RFOC Rejected"
* rfocIsShipped -> "RFOC Sent"
If none of the above -> "OS"

The frontend should be served with these two properties:
* rfccStatus: string with value either "RFCC Accepted", "RFCC Rejected", "RFCC Sent" or "OS"
* rfocStatus: string with value either "RFOC Accepted", "RFOC Rejected", RFOC Sent" or "OS".

Since the frontend should go via dataproxy, it should probably be resolved in dataproxy so FAM view doesn't contain this logic?

Resulting in this:
*  mcPkgNo
* mcPkgId
* Description
* mcStatus
* rfccStatus
* rfocStatus

**Comment by jaysencpp** [comment]
## Suggested change to Handover/Workorders
At the moment we need to resolve each workorder's status based on 
* projectProgress = 100 -> "WO Finished"
* materialStatus containing m12, m13, mn & workOrderStatus containing w04-w10 -> "Material and Workorder OK"
* materialStatus containing m7, m9, m10, m11, mn & workOrderStatus containing w03-w10 -> "Material and Workorder Available"
* if none of above -> "Material and/or Workorder not Available"
 
The frontend should be served with this property:
* woStatus: string with value either "WO Finished", "Material and Workorder OK", "Material and Workorder Available" or "Material and/or Workorder not Available"

Resulting in this:
* workOrderNumber
* workOrderId
* description
* projectProgress
* status

**Comment by ken-mellem** [comment]
Is the entire history here up-to date? Or can we trust the OP?

**Comment by jaysencpp** [comment]
> Is the entire history here up-to date? Or can we trust the OP?

The **data** that is missing (not the DB views) should be: NCR, DocumentID for Tasks, NextToSign

**Comment by ken-mellem** [comment]
@jaysencpp documentID for URL to PCS is now in PROD according to FAM.

**Comment by ken-mellem** [comment]
Closing this - the nextToSign is considered a nice-to-have - but put on hold. See [comment](https://github.com/equinor/cc-components/issues/382#issuecomment-1678704259)
