### ISSUE TITLE
Change data source to CC app api

### ISSUE THREAD

**Issue by jaysencpp** [equinor/cc-components#182]
## Description
When CC app api is ready,  all the apps needs to change their data source to use this instead of mock data and data proxy.
This change might also require a change in the types definition for their objects (in case of different naming)

- [x] Workorder
- [ ] Handover
- [ ] SWCR
- [x] Loop
- [x] Punch
- [ ] MC

**Comment by ken-mellem** [comment]
we track this [here](https://github.com/orgs/equinor/projects/400?pane=issue&itemId=24470063) as well
