### ISSUE TITLE
Workorder - filter on WBS

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#238]
Column "WorkBreakdownStructure" (WBS) is now available in [Completion].[CompletionWorkOrder_v1].
`ICanHaveWorkBreakdownStructureCode | WorkBreakdownStructure | Work breakdown structure code | string`

- [x] enable the column in the table
- [x] enable filtering on this field

## JC Portal

- [x] equinor/lighthouse-client#1368

**Comment by ken-mellem** [comment]
This was requested by the users at Stord. Hence there is a value of implementing this to JC Portal.

**Comment by BenSvend** [comment]
WBS has been added as a filter and a column in the table. Ready for test, can you verify @AreWiv ? 

![Image](https://github.com/equinor/cc-components/assets/133334563/20a7795c-8f26-4af9-a268-9916dc49787e)

**Comment by AreWiv** [comment]
@BenSvend Tested and verified.

**Comment by BenSvend** [comment]
changes have been added to project portal production @ken-mellem.
