### ISSUE TITLE
Default font size shall be 14

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#264]
Default font size shall be 13/14. Sidesheet seems to be 16px+ (all sidesheets)

**Comment by MagnusGjosund** [comment]
![Image](https://user-images.githubusercontent.com/54101675/234006763-ede6070a-cc1b-4598-b354-727f54dc1e24.png)

**Comment by ken-mellem** [comment]
It should be 14px - this is a fairly stupid thing which annoys our test-users.

**Comment by ken-mellem** [comment]
@AreWiv can you please verify this quickly - and have Magnus ship it.

**Comment by AreWiv** [comment]
Reopened for changing status to RfProd.
