### ISSUE TITLE
Punch issues

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#266]
- [x] SWCR: Supplier-dropdown, add "(Blank)"?
- [x] SWCR: Supplier-column very wide

![image](https://user-images.githubusercontent.com/110427825/234002933-828321f2-c23a-45ae-9f72-16177aa08704.png)

![image](https://user-images.githubusercontent.com/110427825/234003030-44b78c59-1581-470a-8ec5-840668cd807c.png)

**Comment by Gustav-Eikaas** [comment]
@MagnusGjosund
