### ISSUE TITLE
feat(handover): Change data source to CC app api

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#328]

**Comment by espenkalle** [comment]
Missing NCr in Fam. Waiting to hear from Jone(?)
SWCR is missing "commissioningPackageUrlId". Need to be joined in.

**Comment by espenkalle** [comment]
Waiting for https://github.com/equinor/cc-components/issues/365 & https://github.com/equinor/cc-components/issues/366
NCr?

Missing fields:
-Need Query url id for Custom_CommissioningPackageQuery.
-Need ProjectSchema for CustomAPI_WorkOrders
-Need commissioningPackageUrlId for Custom_SoftwareChangeRecord
-mcDisciplines in handover pkg?

**Comment by hakonrossebo** [comment]
@aman-riaz

**Comment by espenkalle** [comment]
The "Next to Sign" value comes in a separate endpoint (/details) in the old hanodover app. And that's the only value in the endpoint so seems unnecessary but its perhaps done for a reason :) 

Anyway, need this functionality.

**Comment by aman-riaz** [comment]
-Need Query url id for Custom_CommissioningPackageQuery. DONE

-Need ProjectSchema for CustomAPI_WorkOrders. DONE, but currently unavailable through client due to issue in FAM

-Need commissioningPackageUrlId for Custom_SoftwareChangeRecord. DONE

[https://teams.microsoft.com/l/message/19:7fbe93b3f44c428388c36ef7f13a5879@thread.tacv2/1686137623139?tenantId=3aa4a235-b6e2-48d5-9195-7fcf05b459b0&groupId=3798837d-3217-4190-88f0-b8e37e0ca3da&parentMessageId=1686137623139&teamName=Spine%20-%20FAM%20Data%20Hub&channelName=FAM%20-%20Johan%20Castberg%20Project%20Portal&createdTime=1686137623139&allowXTenantAccess=false](url)

**Comment by ken-mellem** [comment]
@BenSvend can you please give us an indication of ETA for these views?

**Comment by BenSvend** [comment]
@ken-mellem If your're talking about the views regarding unsigned tasks og actions they've already been created under the names:
[Completion].[Custom_UnsignedAction]
[Completion].[Custom_UnsignedCommissioningPackageTask]

If you're talking about another view I am not quite which one that would be.

**Comment by espenkalle** [comment]
Great! But both need "commissioningPackageUrlId " and "projectSchema"

**Comment by BenSvend** [comment]
I am working for Stangeland Today, so I will look at it while I have some spare time, if I can't get it done today I will get it done by tommorow. @espenkalle @ken-mellem

**Comment by BenSvend** [comment]
Views are now created and published in production with the appropriate columns.

**Comment by espenkalle** [comment]
Need mcdisciplines in Custom_CommissioningPackageV2. Should be a array containing full name for the codes. 
mcDisciplinCodes = ['E','P']
mcDisicplin =  ["Electrical", "Piping"] etc..
@BenSvend 

![Image](https://github.com/equinor/cc-components/assets/108390105/c258e847-fa82-4020-9d49-7f606d4ff5e9)

**Comment by AreWiv** [comment]
@espenkalle How to test/verify?

**Comment by ken-mellem** [comment]
@AreWiv @JoneUE has verified first iteration.

**Comment by AreWiv** [comment]
@ken-mellem @JoneUE What does this include? Is this complete or will there be further work?

**Comment by JoneUE** [comment]
This will not have much more work. Just to add some more options in grouping for garden

**Comment by ken-mellem** [comment]
Updated OP with Dependencies (for better tracking purposes).
