### ISSUE TITLE
WO analytics - Earned %

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#362]
![Image](https://github.com/equinor/cc-components/assets/73601851/2adc5f10-3fa4-4938-a212-080e67709ae9)

Earned skal være i %

**Comment by aman-riaz** [comment]
@AreWiv Pushed to production as it was a minor detail. 
https://webserver-fusion-project-portal-prod.radix.equinor.com/apps/workorder/3380fe7d-e5b7-441f-8ce9-a8c3133ee499?tab=powerbi
