### ISSUE TITLE
feat: SWCR serverside (frontend)

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#376]
## Issues
- [x] #514

**Comment by ken-mellem** [comment]
See also 
- equinor/fusion-data-gateway#130

@Gustav-Eikaas is this a duplicate?

**Comment by Gustav-Eikaas** [comment]
No this is for frontend

**Comment by BenSvend** [comment]
I've added Type to [Completion].[Custom_SoftwareChangeRecord_v1], so you don't have to think about this anymore. @aman-riaz
