### ISSUE TITLE
Handover: new fields requested in the views

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#383]
The following fields have been requested a long time ago. It would be good to get this ready for the new serverside version of the application.

- [ ] open PA
- [ ] open PB
- [ ] not signed MCCRs
- [ ] open work orders (< 100%)
- [ ] not signed CPCLs
- [ ] open SWCRs
- [ ] not signed tasks
- [ ] not signed actions
- [ ] open queries
- [ ] remaining mhrs on open work orders

**Comment by Gustav-Eikaas** [comment]
@aman-riaz @BenSvend @espenkalle What is going on here? These new fields needs to be added to the FAM SQL custom view right?

**Comment by espenkalle** [comment]
@ken-mellem Fields are in FAM but need more info. What do we do with them? Filters? Grid? Sidesheet etc

**Comment by ken-mellem** [comment]
This one is based on #13. I am not quite sure how the data should be displayed. @atlewee perhaps you should qualify if this need is real - of if it is simply a "I want it all"-left over from the early days. If so, then I propose we close this for now.

**Comment by atlewee** [comment]
@ken-mellem : leftovers/nice2have/not sure if makes sense :) 
Agree, lets close this.
