### ISSUE TITLE
🎁  Workorder (sidesheet) - query/notification tab

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#384]
Missing data in fam
![MicrosoftTeams-image (7)](https://github.com/equinor/cc-components/assets/89254170/2f3b7a6b-3757-4d44-b438-20d0bba383bf)

**Comment by ken-mellem** [comment]
@Gustav-Eikaas @kjellhaaland can we reuse the same as for Handover?

**Comment by Gustav-Eikaas** [comment]
No idea tbh

**Comment by kjellhaaland** [comment]
@Gustav-Eikaas @ken-mellem I think we can!
There is a flag that we can use to filter out notifications related to workorders i think.
