### ISSUE TITLE
Links in Checklist in Loop sidesheet

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#413]
Missing some data fields. Benjamin has done some changes in Dev. Waiting on FAM

**Comment by AreWiv** [comment]
@MagnusGjosund How to test/verify?

**Comment by MagnusGjosund** [comment]
@AreWiv If the links wasn't there yesterday, you can test again now

**Comment by AreWiv** [comment]
Links to comm pkg, mc pkg and form type available in Loop sidesheet.
