### ISSUE TITLE
Implement heat trace app 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#414]
- [ ] https://github.com/equinor/fusion-data-gateway/issues/157

**Comment by MagnusGjosund** [comment]
Need Heattrace view @aman-riaz

**Comment by aman-riaz** [comment]
@MagnusGjosund Please try to retrieve data from [Completion].[Custom_HeatTrace] in FAM Dev. Let me know if you experience any issues. 
Currently only HT data. Waiting for Pcs/FAM to add the Pipetest connection.

**Comment by MagnusGjosund** [comment]
WIP: Waiting on data and heattrace view. All the data is now hardcoded strings.

Done:
- Table
- Garden
- Sidesheet (header, banner, workordertab and checklist)

Needs to be done in backend:
- KPI
- Filter
- Grouping

Missing in sidesheet:
- Circuit diagram
- 3D

**Comment by MagnusGjosund** [comment]
Need help from our backend heroes to make an API for Heat Trace 🦸‍♂️ Follow the backend issue here https://github.com/equinor/fusion-data-gateway/issues/157

**Comment by MagnusGjosund** [comment]
Made an Epic to this task equinor/lighthouse#291

**Comment by ken-mellem** [comment]
@MagnusGjosund not sure how / where this Issue fits in ... should this be mentioned somewhere or is it a duplicate?

**Comment by MagnusGjosund** [comment]
This was the original issue, but clearly its a bit deficient. This is now a duplicate. I will close it
