### ISSUE TITLE
Frontend:  Grid sorting

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#418]
Add support for grid sorting

**Comment by Gustav-Eikaas** [comment]
add colId MCStatus to the MC column definition in Workorder app
add colid CLStatus to the Checklist column defintiion in Loop
@MagnusGjosund  ask @espenkalle if you need help

**Comment by Gustav-Eikaas** [comment]
@MagnusGjosund

**Comment by MagnusGjosund** [comment]
@Gustav-Eikaas nice tags boi. Next time you can also assigne me so the task appear on the board. Looking at it soon
