### ISSUE TITLE
Create Heat Trace and PipeTest views in FAM

### ISSUE THREAD

**Issue by aman-riaz** [equinor/cc-components#419]
## Heat Trace
- [x] HeatTrace: 2 new SQL views must be created in FAM as this application is new for the project portal

## Pipetest
- [ ] Pipetest: Existing view is specific for JCA, must be scaled for more projects and converted to use ProCoSys new import. 
Requires involvement from FAM to dump JCA and PCS data into same table in FAM

**Comment by aman-riaz** [comment]
Create views for HT and Piping apps as created in [this issue #414](https://github.com/equinor/cc-components/issues/414)

**Comment by aman-riaz** [comment]
**Custom_HeatTrace** in FAM production. 
This view shows all HT cables and their details. 

**Custom_HeatTraceChecklist** in FAM dev. Dependency on other views currently only in dev, therefore cannot be pushed to prod yet. Awaiting contractor data to come into FAM, before view can be pushed to prod. This view shows all checklists related to HT cables, including checklistStep etc. 
@MagnusGjosund @Gustav-Eikaas

**Comment by MagnusGjosund** [comment]
Niiice 😁
