### ISSUE TITLE
Pipetest Analytics

### ISSUE THREAD

**Issue by aman-riaz** [equinor/cc-components#461]
Scale CC pipetest Analytics

**Comment by aman-riaz** [comment]
@ingridhovden  When the report is ready please add it to reports admin and write the global-identifier here so we can create the app for it.

**Comment by aman-riaz** [comment]
@kjellhaaland Can you please add power bi into Pipetest app so we can test the report.

**Comment by Gustav-Eikaas** [comment]
What is the report id @aman-riaz?

**Comment by Gustav-Eikaas** [comment]
Have you published the report @aman-riaz ?

**Comment by kjellhaaland** [comment]
@aman-riaz, i get 404 error message when i add the Pipetest Analytics Report.
Is it published?


![Image](https://github.com/equinor/cc-components/assets/17578087/cfd6bfbe-bd04-4999-ac0c-5d6e951fc8cb)

**Comment by ingridhovden** [comment]
@kjellhaaland, @Gustav-Eikaas The report is now published and ready for test. Can you please try now?

**Comment by kjellhaaland** [comment]
@ingridhovden, i now get it to load, but i dont have access to the report, so i cant view the content.
Am i supposed to be able to view the contents of the report, like the other apps?

I will make a PR, so you can test.

**Comment by kjellhaaland** [comment]
@aman-riaz, @ingridhovden i have added the report top the Pipetest app, but i do not have any rights to view the content of the report.
Can you test?
