### ISSUE TITLE
Pipetest: Grid (Frontend)

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#462]
## Description
Implement the columns according to the draft-layout provided by @MagnusGjosund.

![image](https://github.com/equinor/cc-components/assets/17578087/02484f3f-7508-4a83-8cc7-8e4126b9cf8f)

## Acceptance criteria
The grid includes the fields with correct values:

- [x] Pipetest
- [x] Description
- [x] Priority
- [ ] Location
- [x] Checklist status
- [x] Current Step
- [x] RFC
- [ ] HT cables

**Comment by kjellhaaland** [comment]
The type _Custom_PipetestV1_ from FAM is potentially missing some fields.

I have deduced the following mappings from _Custom_PipetestV1_ to the columns in the grid:

- [ ] Pipetest <-> **Id**
- [ ] Description <-> Missing?
- [ ] Priority <-> Priority1
- [ ] Location <-> Missing?
- [ ] Checklist status <-> MechanicalCompletionStatus
- [ ] Current step <-> Missing?
- [ ] RFC <-> Unsure about the field
- [ ] HT cables <-> Missing?

@MagnusGjosund can you help me clearify the rest of the field mappings, and how to get the rest?
Please edit this comment with the correct mapping, and check them when they are verified.

**Comment by aman-riaz** [comment]
Walk-through of Pipetest app by Kjell to understand data requirement. 
Discussed the mappings mentioned above and clarified. 

Following fields are missing and will be added to Custom_Pipetest_v1:

Pipetest Description 
HT cables 

(postponed) 
Checklist status
ChecklistStep

**Comment by kjellhaaland** [comment]
Waiting for fields from FAM.
Progress tracked in: equinor/fusion-data-gateway#468

**Comment by kjellhaaland** [comment]
New fields added to FAM, but some is still missing.

Progress tracked in: equinor/fusion-data-gateway#468

**Comment by kjellhaaland** [comment]
Closing this issue as it is now implemented and ready for test 🚀
Results from testing, and any potential changes that needs to be made is tracked in equinor/fusion-data-gateway#179
