### ISSUE TITLE
Workorder: Wrong material status in sidesheet 

### ISSUE THREAD

**Issue by idrisbo** [equinor/cc-components#474]
Main issue: https://github.com/equinor/lighthouse/issues/187

All material status is shown as "Not Available", even if the material(s) are available.

**Comment by AreWiv** [comment]
@idrisbo How do I test this?

**Comment by AreWiv** [comment]
Tested according to description.
Reopened to set status to Ready for Prod.

**Comment by AreWiv** [comment]
Close as Merged and Done.
