### ISSUE TITLE
SWCR Analytics scroll bug/missing functionality

### ISSUE THREAD

**Issue by BenSvend** [equinor/cc-components#499]
![Image](https://github.com/equinor/cc-components/assets/133334563/dff8630b-d4ab-442b-9d87-131739297ca4)

When selecting filters, users are unable to view a significant portion of the report. We should enhance the user experience by enabling scrolling when the filters tab is open.

**Comment by Gustav-Eikaas** [comment]
SWCR analytics is still running fusion-workspace@0.24, verify if this issue persists in 3.x.x^

**Comment by Gustav-Eikaas** [comment]
Dont touch this until SWCR is server side

**Comment by Gustav-Eikaas** [comment]
Verify if this bug still exists. It might have been fixed going serverside

**Comment by JoneUE** [comment]
Still unable to scroll the report when filter is expanded, but this should be fixed when SWCR is changed to new version of workspace?

**Comment by Gustav-Eikaas** [comment]
@JoneUE Yes

**Comment by ken-mellem** [comment]
Agreed to close.
