### ISSUE TITLE
SWCR : Add Commpkg Area to filters 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#514]
Add Commpkg Area to filters.

Currently missing this datafield in SWCR to add this filter. Needs to be added when scaling the application

**Comment by BenSvend** [comment]
CommissioningPackageArea has been added to SWCR Test.

Will be put into production when #376 is closed

**Comment by ken-mellem** [comment]
I will close this to clean up. Verified in TEST. Expecting it in PROD.
