### ISSUE TITLE
🎁 [punch]: Enable 3D in sidesheet

### ISSUE THREAD

**Issue by Noggling** [equinor/cc-components#582]
The baseline 3D Model-viewer component is finished, and available for use in all cc-applications.
Implemented in PR https://github.com/equinor/cc-components/pull/774

To use it in the rest of the applications, the following needs to be done:
1. Create a new endpoint in each of the apps returning the relevant tags for a given entity. (/echo endpoint, see work-order implementation)
2. Enable the model-viewer in application config.
3. Add the ModelViewerTab to each sidesheet with relevant props.

In order to implement this, PO must provide a list of which types of tags that are relevant for 3D for each application.

**Comment by kjellhaaland** [comment]
@jone, which tags are relevant for 3D for this application?

**Comment by atlewee** [comment]
@kjellhaaland Punch is attached to a checklist/mccr.. and that checklist is for one single tag.
( So for punch it will always be 1 tag, never 0 and never more than one )

**Comment by kjellhaaland** [comment]
@JoneUE, ModelViewer for Punch is now ready for test.

Link to test: https://webserver-fusion-project-portal-test.radix.equinor.com/apps/punch

Can you test and verify that its ok?

**Comment by JoneUE** [comment]
Looks good
