### ISSUE TITLE
[Loop]::bug: WO Not displaying in Loop sidesheet

### ISSUE THREAD

**Issue by BenSvend** [equinor/cc-components#586]
![image](https://github.com/equinor/cc-components/assets/89254170/ef053729-bd6b-4771-98b9-ef1a9ddc8b79)

**Comment by BenSvend** [comment]
@AreWiv I've fixed the issue regarding missing WO data. Can you test? https://webserver-fusion-project-portal-test.radix.equinor.com/apps/loop/94dd5f4d-17f1-4312-bf75-ad75f4d9572c?tab=grid&item=ed187f43-a32e-c84b-e053-2810000a69dd

**Comment by AreWiv** [comment]
Verified. @BenSvend It would help if you indicated in the screen shot what/where the WO no was missing - e.g with a red circle.
