### ISSUE TITLE
🎁: Handover: Highlight non-counting scope

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#613]
## Expected outcome
User can easily see CommPks that are not fully complete. (has non-counting scope)

## Business Value / Developer Experience
In ProCoSys the administrator can mark Form.Responsible codes counting or non-counting.
eksample: responsible code "KSI" is currently Counting but  "KSIC" is not.
![image](https://github.com/equinor/cc-components/assets/11732817/9d2b64a0-96c4-4717-b752-0b244b6e270a)
![image](https://github.com/equinor/cc-components/assets/11732817/941aa562-dae8-4f05-b811-25537311a0a8)
(This information is currently not possible to extract from ProCoSys, and is not sent to FAM)

All MC packages and CommPackages has a field called "mcStatus" calculated from the worst status of checklists in that package.
The counting/non-counting flag determines what checklists contributes to the aggregated status.

This means that some commPks might have mcStatus: OK, but it actually contains non-counting checklists with status OS.

In the Garden view the mcStatus is currently shown as the first "dot" on the right side:
![image](https://github.com/equinor/cc-components/assets/11732817/5c3cb287-c07e-48a3-92a3-656a8c8df2db)
Tooltip explaining this:
![image](https://github.com/equinor/cc-components/assets/11732817/b98d92f9-1287-4c42-869e-a19b48a33af4)

We should find a way to hightlight if the package is green but the dot is not 100% correct. Something like this:
![image](https://github.com/equinor/cc-components/assets/11732817/89583368-645e-406a-9719-64e59e6f04d1)
Or a star / caviat symbol?

## Possible solution
To find out if the warning should be shown, the FAM view could add a new field called "worstChecklistStatus" calculated from checklists connected to the commPk.
If worstChecklistStatus is worse than Commpk.McStatus we show the warning for non-counting scope.
( Status from worst to best: OS,PA,PB,OK )

## Acceptance Criteria
- [ ] It is possible to see if there is outstanding non-counting scope hidden behind a good mcStatus
- [ ] Spot check that commPks from the following search has the new warning:

![image](https://github.com/equinor/cc-components/assets/11732817/7f1083e2-6eee-4c36-9604-0356cc3d8448)
https://procosys.equinor.com/JOHAN_CASTBERG/Search/Load?searchId=120462

**Comment by ken-mellem** [comment]
UX should have a say in how this visually could be displayed. @chriispychiicken 
@aman-riaz @BenSvend could you assess if this is fairly straight forward to implement in the view in question? 

@atlewee you have not specified portal - but I vaguely remember you indicated JC Portal. Also, consider the delivered value vs cost and what the implication is if this is not implemented.

**Comment by atlewee** [comment]
@chriispychiicken 
It does not have to be visualised in the garden itself that was just an example, maybe a warning in the sidesheet is a better solution.?.

Probably a lot simpler view that way (Only one commPk, not the full dataset)

@ken-mellem 
The request is coming from Castberg. And there is more tweeks coming that we should have both places.
I think we should consider upgrading to the scaled versions of CC apps in JC portal so that we only need to maintain one set.

**Comment by chriispychiicken** [comment]
I can talk to Lotte about it and see if we can come up with a good solution :) It Is a bit tricky, as adding even more to an already overpacked component will make everything look chaotic, so we have to find a good way to add it.

**Comment by ken-mellem** [comment]
@BenSvend could you assist here with the calculation?

**Comment by BenSvend** [comment]
Yes @ken-mellem, but I am not sure what view i need to do the calculations in? @atlewee do you know which view it is?

**Comment by chriispychiicken** [comment]
@atlewee is it important for the user to see that the status is not 100% ok in the garden view or is it most important to be able to see it in the sidesheet?

**Comment by atlewee** [comment]
@chriispychiicken McStatus in sidesheet is good enough.. Maybe a warning somewhere here with a tooltip on the warning with an explanation:
![image](https://github.com/equinor/cc-components/assets/11732817/f5085361-4c52-4764-9f7b-770e36ac3af1)

@BenSvend 
Tror det blir cc-backend på ProjectPortal:
https://backend-fusion-data-gateway-prod.radix.equinor.com/api/contexts/{context}/handover/{commpk}
JC:
https://fusion-s-dataproxy-fprd.azurewebsites.net/api/contexts/{context}/handover/{commpk}/details

**Comment by atlewee** [comment]
@chriispychiicken Har noen brukere som etterspør status på denne. Fikk dere kjangs å se på noe design?

**Comment by chriispychiicken** [comment]
> @chriispychiicken Har noen brukere som etterspør status på denne. Fikk dere kjangs å se på noe design?

Wokring on it now, Ill put in some pictures of deisgn ila dagen :)

**Comment by chriispychiicken** [comment]
![bilde](https://github.com/equinor/cc-components/assets/131761693/44bc613f-3a41-430e-bfe5-add89412c49b)
 noe sånt?

**Comment by ken-mellem** [comment]
@chriispychiicken so - if you have an approved UX design, we should work on the flow here - @espenkalle is finalizing the Handover app - this will be a first new good enhancement we should aim to add as the app is to be made available on JC-Portal.

**Comment by ken-mellem** [comment]
Updated state to Ready for Test @espenkalle - please set appropriate state
