### ISSUE TITLE
🐛: Horizontal scrollbar in advanced filter is missing

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#616]
## Description
![image](https://github.com/equinor/cc-components/assets/11732817/afa7deb6-0ccf-4f5f-9657-17042e626258)

## Reproduce
Open Workorder and advanced filter

## Expected behavior
Scrollbar appearing

**Comment by ken-mellem** [comment]
This is generic for all apps.

**Comment by Gustav-Eikaas** [comment]
Im not sure I understand, are you referring to the vertical scrollbars in the filter groups?

**Comment by atlewee** [comment]
The arrow points to where a scrollbar should be displayed… (where the red lines are drawn)
