### ISSUE TITLE
🎁: Handover: Show missing punchOuts on commPk/mcPk (JC&PP)

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#619]
## Expected outcome
Users of handover app can see if a commissioning package is missing punchOut/IPO

(_Punchout means a formal QA-session where contractor show off the work they have done to the customer in the field and that group together decides what, if any punch needs to be registered against that work.
IPO = Invitation for PunchOut_)

## Business Value / Developer Experience
Today, users have to manually open all mcPackages in a commPk one by one in ProCoSys to verify there is an actual date in M02 milestone:
The M02 status show if punchout is accepted:
![image](https://github.com/equinor/cc-components/assets/11732817/3dc66521-97ec-4e5a-9ef3-6b7f328ce126)
MC packages with discipline code "A" should not be considered as they do not have punchOuts

## Suggested solution
Maybe we could show the M02.actualDate in the MCpackage tab? 
![image](https://github.com/equinor/cc-components/assets/11732817/833fb52a-8968-49c6-9438-b349fe6f5d38)

And to show something on the details page.
List outstanding mcPackages on a row, or have something like Punchout status: "3 mcPackages missing punchOut" ?
![image](https://github.com/equinor/cc-components/assets/11732817/a1ed2a95-a6df-47c5-bc4f-6229200e5931)

## Acceptance Criteria
- [ ] Easier to find out if and where we have mcPackages with not accepted punchOut
- [ ] MC packages with discipline A (Administration) should not be included

**Comment by espenkalle** [comment]
@atlewee We dont have the date in our current view, but we have a boolean for if the actualdate is set. 
![image](https://github.com/equinor/cc-components/assets/108390105/0b30439c-679a-4f3f-817d-7ec73737bbe0)

**Comment by BenSvend** [comment]
RemainingPunchOutCount has been added to [Completion_PreprocessCode].[Custom_CommissioningPackage]. You should be able to find it in [Completion].[Custom_CommissioningPackage_v3] when FAM pushes the changes to Prod @espenkalle.
