### ISSUE TITLE
🎁: Punch - Two new filters: FormType and Discipline

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#626]
## Expected outcome
Possible to filter punch on FormType and Discipline

## Business Value / Developer Experience
Several users on Stord tell Edward that they can not use the JC-portal to find their punches because it is not possible to filter on FromType and Discipline.
There was 3 separate requests from 3 different people that asked for this same filters in various ways.

I think both these fields is already available in punch views (FAM)
Functionallity wanted in JC and PP

## Acceptance Criteria
- [x] Possible to filter on formType
- [x] Possible to filter on discipline
- [x] formType can be shown as column in table
- [x] discipline can be shown as column in table

**Comment by MagnusGjosund** [comment]
Do you want to have these two new filters in quick filter as well? If yes, which two others do you want to remove from quick filter?

**Comment by atlewee** [comment]
Only Discipline whould be required in the quick filter. But it is less important than the ones there already.
It is ok to not add them to quick filters

**Comment by MagnusGjosund** [comment]
Done in PP and JC. Waiting on PR approvals

**Comment by ken-mellem** [comment]
@MagnusGjosund please link PRs and close issue.

**Comment by MagnusGjosund** [comment]
PR PP frontend: https://github.com/equinor/cc-components/commit/95716c86eb84046d06c41c4a87e0ae3b26d55405
PR PP backend: https://github.com/equinor/fusion-data-gateway/commit/ce686718b2016088017059d05b14a85b6ac239ec and https://github.com/equinor/fusion-data-gateway/commit/c153fb817ccc28d546cb167da8156425b24c3362
PR JC: https://github.com/equinor/lighthouse-client/commit/5f3137c0b9ed50e7751b9e047e7c6f3700aac39f
