### ISSUE TITLE
✨: Create app Workorder area overview

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#628]
## Expected outcome
- [x] Create PBI report
- [x] Make application

[More information](https://statoilsrm.sharepoint.com/sites/FusioniPRD/Dashboards%20and%20MPP/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1687341305262&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FFusioniPRD%2FDashboards%20and%20MPP%2FReports%20Into%20Fusion%20%28RIF%29%2FCCH%2FProject%20Portal%2FOGP%20reports&viewid=f853cde1%2D6ede%2D47a2%2Da60a%2D7a9b1e81dc92)

## Business Value / Developer Experience
A prioritized PBI report by OGP, this is a pilot that can be sacaled to other projects when 2D and gantt is added to workspace

## Acceptance Criteria

- [ ] PBI report loads
- [ ] Filters are okay
- [ ] App is available for OGP

**Comment by JoneUE** [comment]
Får du prioritert opp denne? dette er noe OGP ønsker seg

**Comment by aman-riaz** [comment]
App and report are ready and will soon be  availbale in test @JoneUE

**Comment by JoneUE** [comment]
@aman-riaz Can send this to produciton when it's ready

**Comment by aman-riaz** [comment]
Signoff meeting 16.11 with Jone Ueland, Håvard Tonning & Aman Riaz
