### ISSUE TITLE
🎁: Mechanical completion workspace filters enhancement

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#644]
## Expected outcome
- [x] Add Commissioning phase as filter

Filter name: Comm Phase

Quick filter: No
Exist in Custom_MechanicalCompletionPackage_v1 as CommisioningPhase

- [x] Rename Discipline to MC Discipline
- [x] Add Identifier as filter

## Acceptance Criteria
Filter is added to MC workspace

- [x] when selecting 
- [x] items which covers
- [x] the expected outcome

**Comment by ken-mellem** [comment]
Att Commissioning phase as filter - SNOW ticket RITM3057387 - also wanted for Fusion Legacy MC Garden. However, this will only be done in the new scaled version.

**Comment by espenkalle** [comment]
Added in backend. Will appear in app when frontend is deployed
