### ISSUE TITLE
🎁: Workorder - New filter: System

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#657]
## Expected outcome
Possible to filter on System

## Business Value / Developer Experience
It is useful to know what systems a WO is for
If you are system resposible, you want to quickly find the relevant WO's for you.
If you want to find all work related to say a safety system like Fire&Gas, it is nice to quickly filter out those.

Info: System is a muli-field
WO.systems = UNION between WO.commPk.system AND WO.checklists.sytem

## Acceptance Criteria
- [x] Possible to filter WO on systems
- [x] Systems is shown in table

**Comment by MagnusGjosund** [comment]
@BenSvend we need a new column in CustomAPI_WorkOrdersV1

**Comment by BenSvend** [comment]
Looking into it.

**Comment by BenSvend** [comment]
Systems is now available in Workorder test in the Table, and as a filter. Can you verify @atlewee ?

**Comment by ken-mellem** [comment]
Verified. Also in PROD.
