### ISSUE TITLE
🎁: Installation: added Location Area tab

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#667]
## Expected outcome
Have added a location Area tab. and made new version here: https://statoilsrm.sharepoint.com/sites/JohanCastbergProjectPortal/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FJohanCastbergProjectPortal%2FShared%20Documents%2FGeneral%2FPBI%2FReports%2FInstallation&viewid=a0a01bb9%2De999%2D4e04%2D801a%2D193b51e33d19

**Comment by aman-riaz** [comment]
in prod: https://jc.fusion.equinor.com/ConstructionAndCommissioning/installation
