### ISSUE TITLE
🎁: Mechanical completion changes

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#675]
## Expected outcome
Seem that m01_actual and m02 actual have changed from "Yes", "No" to 1,0. 

Measures in the PBI also need to update this then

**Comment by JoneUE** [comment]
Can be sent to production

**Comment by JoneUE** [comment]
I have fixed this and added a filter for C01 status on countdown page. and sorted by c01 date. new version added https://statoilsrm.sharepoint.com/sites/FusioniPRD/Dashboards%20and%20MPP/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1687341305262&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FFusioniPRD%2FDashboards%20and%20MPP%2FReports%20Into%20Fusion%20%28RIF%29%2FCCH%2FProject%20Portal%2FCC%20Reports%2FMechanical%20completion&viewid=f853cde1%2D6ede%2D47a2%2Da60a%2D7a9b1e81dc92

**Comment by JoneUE** [comment]
![Image](https://github.com/equinor/cc-components/assets/73601851/3eb50510-cc36-4ef0-9e7b-22b7e01029ec)

Display these as Yes or No

**Comment by aman-riaz** [comment]
in prod in Project Portal: https://project.fusion.equinor.com/apps/mechanical-completion/c5365fa9-b6da-4ca3-bebb-d783a63ae467
