### ISSUE TITLE
🎁: Progress status: added Earned by plan

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#677]
## Expected outcome
Added two new tabs to Progress summary report 

For JC portal
Ready for production

https://statoilsrm.sharepoint.com/sites/JohanCastbergProjectPortal/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FJohanCastbergProjectPortal%2FShared%20Documents%2FGeneral%2FPBI%2FReports%2FProgress%20status&viewid=a0a01bb9%2De999%2D4e04%2D801a%2D193b51e33d19

**Comment by aman-riaz** [comment]
in prod: https://jc.fusion.equinor.com/ProjectControl/progress-summary
