### ISSUE TITLE
🎁: Handover - Exclamation mark

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#679]
## Expected outcome
It is clear to the user what package the exclamation mark belongs to
Today users are not sure if this belongs to the left or right package:
![image](https://github.com/equinor/cc-components/assets/11732817/fb230689-d8a8-4357-bb80-730c6086b5fb)

## Business Value / Developer Experience
Prevent user from reading the data wrong

## Acceptance Criteria
- [x] It is clear what package the exclamation/warning belongs to

**Comment by espenkalle** [comment]
https://github.com/equinor/cc-components/pull/683
