### ISSUE TITLE
🎁: Tags analytics: add clickable link to ProCoSys

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#681]
## Expected outcome
Add link to ProCoSys in browser

![Image](https://github.com/equinor/cc-components/assets/73601851/4d477a8e-2394-409c-b21d-fdbaa934c74a)

**Comment by JoneUE** [comment]
@aman-riaz Jeg har fikset det og lagt til slik at tabellen kan expande til å vise checklistene også. 
Det er en forespørsel fra Aker så vil gjerne få den ut fort

**Comment by aman-riaz** [comment]
In prod: https://jc.fusion.equinor.com/ConstructionAndCommissioning/tags-analytics
