### ISSUE TITLE
🐛: Mechanical Completion. Filters showing data for other Projects

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#685]
## Description

![Image](https://github.com/equinor/cc-components/assets/73601851/569dc337-3cb9-4afa-9a42-b3b9b2359c0f)

**Comment by JoneUE** [comment]
![Image](https://github.com/equinor/cc-components/assets/73601851/c10d5d0a-fa43-48b8-a553-a0352579ddce)

And these KPIs have a bug, I'm guessing since it's changed back to Yes, No from 1,0

**Comment by ken-mellem** [comment]
@aman-riaz I will then close this
