### ISSUE TITLE
🐛: Handover: Wrong CommPk status in garden

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#696]
Old handover app in JC is showing correct (left), the new handover app (middle) seems to be showing "dynamicCommissioningStatus"
but should be showing "CommPkStatus"
![image](https://github.com/equinor/cc-components/assets/11732817/7a1c5f01-a8eb-4b6f-ba14-61dd5701c64a)

**Comment by espenkalle** [comment]
@aman-riaz @BenSvend need to update Custom_CommissioningPackageV3

**Comment by espenkalle** [comment]
https://github.com/equinor/cc-components/pull/703
