### ISSUE TITLE
🎁: Commissioning analytics: Added system number to description

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#699]
## Expected outcome

![Image](https://github.com/equinor/cc-components/assets/73601851/95208fee-c5f1-46e4-aeb2-f4be4d629a0b)

Added system number to description

**Comment by aman-riaz** [comment]
@JoneUE  can you please describe which page this is in commissioning analytics. I cannot seem to find this table in the report.

**Comment by JoneUE** [comment]
![image](https://github.com/equinor/cc-components/assets/73601851/8cb69915-1b5d-4404-a7ae-2eb1faa6f729)
The dasboard page

**Comment by aman-riaz** [comment]
in prod https://jc.fusion.equinor.com/ConstructionAndCommissioning/commissioning-analytics
