### ISSUE TITLE
🎁: Handover - Add RFC KPI's

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#704]
## Expected outcome
User can also see RFC KPI's (not just RFO)
![image](https://github.com/equinor/cc-components/assets/11732817/6d59b1f8-292b-4d7f-99c3-6633afbd5168)

## Acceptance Criteria

- [x] Total CP
--- RFC ---
- [x] NotSent
- [x] Partly Sent
- [x] Sent
- [x] Partly Accepted
- [x] Accepted
- [x] Overdue (changes based on planned/forecast)
--- RFO ---
- [x] NotSent
- [x] Partly Sent
- [x] Sent
- [x] Partly Accepted
- [x] Accepted
- [x] Overdue (changes based on planned/forecast)

**Comment by espenkalle** [comment]
With that many kpis we should probably address this workplace issue first. 
Need to make the kpi "bar" scrollable  

![image](https://github.com/equinor/cc-components/assets/108390105/df910117-e857-455e-af67-457bac33638d)

**Comment by atlewee** [comment]
I think I would prefer the KPI bar to just stay fixed/clip and those "Analytics"/"Garden" buttons to be hidden when sidesheet is open.
(Long term fix is to split Handover into RFCC and RFOC)

**Comment by Gustav-Eikaas** [comment]
`(Long term fix is to split Handover into RFCC and RFOC)` 😮

**Comment by atlewee** [comment]
Something in the middle could be to have viewMode as a setting in the new viwSettings thing on the right.. 
Mode: Handover to Commissioning | Handover to Operations

**Comment by ken-mellem** [comment]
@atlewee please UAT
