### ISSUE TITLE
🐛: Navigation between applications in topbar not working

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#737]
## Description

![Image](https://github.com/equinor/fusion-workspace/assets/73601851/a65ac2ff-0564-47c3-be3b-7957ce03ddc0)

Selecting Handover just loads Mechanical Completion again

But going from Handover to Mechanical completion works

**Comment by Noggling** [comment]
@Gustav-Eikaas This issue is history replace issue on Mechanical completion unmount. not a portal issue

**Comment by Gustav-Eikaas** [comment]
Oh yeah, you're right. Will be fixed when MC and SWCR is finished. Which is soon. #638 #604
