### ISSUE TITLE
🖌️ (MC) : Add tab for MCCR's in sidesheet

### ISSUE THREAD

**Issue by espenkalle** [equinor/cc-components#745]
## Current state 
Missing mccr in sidesheet

## Desired state 
https://github.com/equinor/CC/issues/64

**Comment by espenkalle** [comment]
Bruk Completion.Custom_Checklist. Så sende in et parameter på FormularGroup = "MCCR"

@BenSvend Kan du legge til mechanicalcompletionpackageUrlId i det viewet

**Comment by ken-mellem** [comment]
@espenkalle Jone kommenterte på originalen. (note to self - we must work with the same issue!)

> It is just missing a url for checklist on the FormType column, other than that it's ready

Kan du få lagt dette til?

**Comment by espenkalle** [comment]
added url for checklist
