### ISSUE TITLE
🐛: Sidesheet table autosizing

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#751]
There should be maxwidths on autosizing columns
![image](https://github.com/equinor/cc-components/assets/89254170/46a8e3b0-e1b5-4141-adb3-e6476402c84c)

**Comment by MagnusGjosund** [comment]
You sure its not autosizing? Can't reproduce

![Image](https://github.com/equinor/cc-components/assets/54101675/16d2b5a8-dc23-4312-8297-40461f9c6746)

Can't find any handovers with items in the swcr tab in test/prod, only on localhost.

**Comment by Gustav-Eikaas** [comment]
We did bump the ag grid version so maybe it got fixed

**Comment by MagnusGjosund** [comment]
Seems like bumping the version fixed it. I will close the issue
