### ISSUE TITLE
🐛: Work order data missing

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#773]
## Description

![Image](https://github.com/equinor/cc-components/assets/73601851/461c722c-4078-4bbf-a1ab-b9e92ddfbd4e)

![Image](https://github.com/equinor/cc-components/assets/73601851/54b5f7b7-74b5-4ef5-b2a0-db2293e97212)

There is a missmatch in data for current week

## Reproduce
The screenshots show what data is in Project Portal and what is in ProCoSys. There are a few missing in Project Portal

## Expected behavior
Same amount of Work orders in Project Portal as Fusion for Work orders in PCON responsible and with less than 100% progress

**Comment by kjellhaaland** [comment]
@JoneUE, it seems that the provided screenshots are both the same screenshot? 
What context/project is this data from?

**Comment by JoneUE** [comment]
Yeah I realized, but it seem there isn't an issue anymore
