### ISSUE TITLE
🔗: (SWCR) Request Data in FAM

### ISSUE THREAD

**Issue by ken-mellem** [equinor/cc-components#782]
# References
- https://github.com/equinor/lighthouse/discussions/464
- https://github.com/equinor/cc-components/issues/741

# Summary

Users at Johan Castberg identified that the SWCR.Status was not correctly updated on certain ProCoSys events. The users would then see wrong status. See equinor/cc-components#741 for more information

## Proposal

From ProCoSys Export the required link between SWCR status and classification.

## External reference

- https://statoildeveloper.visualstudio.com/Statoil.NextGenProCoSys/_workitems/edit/109025

**Comment by ken-mellem** [comment]
PCS has a meeting Monday with SA and POs.

**Comment by ken-mellem** [comment]
There appears to be happening something on PCS side - they will likely re-send det full dataset to get correct status. See WI link in OP.

**Comment by Gustav-Eikaas** [comment]
Any news on this? The old unscaled version of SWCR is still in production. We would like to replace this as soon as possible

**Comment by ken-mellem** [comment]
I forwarded to ProCoSys teamlead - awaiting reply.

**Comment by ken-mellem** [comment]
Have been told this is done - @Gustav-Eikaas I suspect we need to do an activity here?

**Comment by Gustav-Eikaas** [comment]
Yes we have to do the following in order

- [ ] FAM reintroduces this field in their baseviews
- [ ] We reintroduce this field in our sql views
- [ ] some c# and ts code to present it

**Comment by ken-mellem** [comment]
Follow up: 
- https://github.com/equinor/fusion-data-gateway/issues/653
