### ISSUE TITLE
🐛: Workorder - Filters does not work correctly

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#787]
## Description
When applying filters we sometimes get wrong result

## Reproduce
User (Kjartan Algrøy) gave me this: (Tried it and get the same issue myself)
![image](https://github.com/equinor/cc-components/assets/11732817/5a0833fe-1d0b-4564-8e9a-78f6594d7d42)
![image](https://github.com/equinor/cc-components/assets/11732817/bcb3a41a-0014-4d97-8fba-e947ba8d257a)

It is also a similar issue with Category.. If you filter on Category "HV" this workoder should be listed but is not.

## Expected behavior
All WO with milestone "F108-NEW-ZSI" should be displayed when filtering only for that.

**Comment by Gustav-Eikaas** [comment]
25615730
F108-NEW-ZSI

**Comment by Gustav-Eikaas** [comment]
Merged a PR temporarily removing the systems filter. Will make a proper fix after christmas holiday
