### ISSUE TITLE
✨: Fusion Featurelog 

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#794]
## Expected outcome
PowerBi product owner is interested in seeing usage statistics for apps used in our Portal. In Fusion there is a powerbi report that reads app usage and presents it. We need to write an integration to get our data into this service.

Need to reach out to Fusion Core to get specifics about this one

EDIT:
There is an endpoint to send metrics that are collected into the powerbi usage report. It's the portals responsibility to call this endpoint. Fusion Project Portal does not log to this endpoint at the moment and shouldnt either because this endpoint doesnt handle multiple portals. (yet)

After talking to Odin there is really only 2 solutions to this:

1. Make something ourselves.
2. Wait for app management v2. (Will discuss this with Joachim) (Will probably take months/years)

**Comment by Htonning** [comment]
The reason we request this integration to the Fusion Featurelog / User Statistics Report is that we have product owners (e.g. Jens Sverre Hauge for ADS) who would like to see if and how the reports are used - and use this insights as input to decide if we need to communicate better to our target audience to realize the value that the reports could provide

**Comment by Gustav-Eikaas** [comment]
Possible solution: We can log to the feature endpoint and ask the powerplatform team to use the "url" property to separate which portal the events were sourced from. Should probably run this by Hans to make sure he is informed.

**Comment by ken-mellem** [comment]
Duplicate.
