### ISSUE TITLE
🎁: Handover filters

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#800]
## Expected outcome

       Filters = Filter name i workspace
- [x] MC Discipline = Disciplines 
- [x] Supplier
- [x] Handover Status = Comm pkg Status
- [x] Comm Status 
- [x] MC Status
- [x] Comm Responsible
- [x] Comm Location = Area
- [x] Comm Phase = Phase
- [x] Comm System = System
- [x] Comm SubSystem
- [x] Comm Priority 1
- [x] Comm Priority 2
- [x] Comm Priority 3
- [x] Facility
- [x] Project
- [x] Comm Identifier

Add these to workspace

![Image](https://github.com/equinor/cc-components/assets/73601851/3aaf8878-1d2f-4876-a027-679c013246a5)

- [x] PBI
- [ ] Workspace

**Comment by aman-riaz** [comment]
I have added the filters for PBI in test:   
https://webserver-fusion-project-portal-test.radix.equinor.com/apps/handover/ce31b83a-b6cd-4267-89f3-db308edf721e?tab=powerbi

@JoneUE With longer filter names, the whole filters name is not visible.

**Comment by aman-riaz** [comment]
@espenkalle @Gustav-Eikaas are these filters available for the workspace? if yes, can you please close the issue.

**Comment by espenkalle** [comment]
Ser på det etter lunsj :)

**Comment by ken-mellem** [comment]
@atlewee

**Comment by JoneUE** [comment]
If Comm Area is renamed to comm Location, it is good to go. This is due to commonLib using the name Location for areas

**Comment by Gustav-Eikaas** [comment]
@JoneUE We have this file to try and standardize naming across applications. 
https://github.com/equinor/fusion-data-gateway/blob/main/src/CCApplications.Applications/Common/Domain/DomainNames.cs

**Comment by JoneUE** [comment]
@Gustav-Eikaas I can look at it, but if you're in doubt about someone, I'm trying to standardize with what is in ProCoSys. so you can also look what names they use. For example ChecklistStatus would be Form Status

**Comment by JoneUE** [comment]
But also the easy answer would be that all columns that belong to the checklist table, should start with Form, Tag with Tag, SWCR with SWCR, Punch with PL, Work Order with WO, Mcpkg with MC and Commpkg with Comm
