### ISSUE TITLE
🐛: PBI quickfilters are cramped up

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#813]
## Description

Why are the filters in WO analyics so cramped?

![image](https://github.com/equinor/cc-components/assets/11732817/2b36cc84-7d85-40f6-9591-cfb159d36e6a)

**Comment by JoneUE** [comment]
@Gustav-Eikaas Is this a general Workspace thing for PBI?

**Comment by Gustav-Eikaas** [comment]
Yeah, some css bug

**Comment by Gustav-Eikaas** [comment]
No scrollbar, use grid and auto-fill/fit

**Comment by JoneUE** [comment]
Is every filter supposed to show in the Quickfilter?

**Comment by Gustav-Eikaas** [comment]
No it's supposed to just fit as many as possible without them being cramped up

**Comment by JoneUE** [comment]
@ken-mellem is anyone looking at this?

**Comment by MagnusGjosund** [comment]
I can take a look at it on monday :)

**Comment by kjellhaaland** [comment]
@JoneUE, this fix is now ready for verification in test.
 Can you test and verify it looks ok?

[Link to test](https://webserver-fusion-project-portal-test.radix.equinor.com/apps/workorder/94dd5f4d-17f1-4312-bf75-ad75f4d9572c?tab=powerbi)

_Note to self: If ok, i will have to bump fusion-workspace version on cc-reports as well before it is available in all reports._

**Comment by kjellhaaland** [comment]
Approved by @JoneUE in Teams.
Merging with main
