### ISSUE TITLE
🎁: HeatTrace - New tab "Heated tags"

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#827]
## Expected outcome
Add a new tab with the name "Heated tags". This tab should show all the tags the heat trace a heating. Use the Custom_HeatTraceCableServiceCompletionTag view. I think the tab should show a table. 

For more information, ask Jone or Atle

## Business Value / Developer Experience
Show additional relevant data.

## Acceptance Criteria
Jone or Atle needs to verify :)

**Comment by JoneUE** [comment]
Custom_HeatTraceCableServiceCompletionTag can be used, but there is also a need to add a column fro Handover status, based on mcpkg. This is so that they can know who is the owner of the Tag, is it construction, commissioning or Operations

**Comment by kjellhaaland** [comment]
### Status update

- I have created/modified a new view **CCApp.HeatTraceCableServiceCompletionTag** that are availible in Self-Service.
- Implemented a new API endpoint for heated tags in fusion-data-gateway.
- Added a new tab for **Heated tags** in Heat-Trace sidesheet.

#### Pull Requests
self-service: https://github.com/equinor/fusion-fam-self-service/pull/286
fusion-data-gateway: https://github.com/equinor/fusion-data-gateway/pull/664
cc-components: https://github.com/equinor/cc-components/pull/1081

![image](https://github.com/user-attachments/assets/5e3964e1-9e3f-4faa-b809-11f2565817e9)

**Comment by kjellhaaland** [comment]
@JoneUE can you verify that it looks and works ok?
@aman-riaz, can you review https://github.com/equinor/fusion-fam-self-service/pull/286 to verify that the new view looks ok?

**Comment by kjellhaaland** [comment]
This is now merged into production.
I have tested and verified that it works.

@JoneUE FYI
