### ISSUE TITLE
🎁: HeatTrace - Enable searching for description in table search

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#829]
## Expected outcome
Investigate the possibility to search for description in table view. I think its only enabled for tag(id) search.
![image](https://github.com/equinor/cc-components/assets/54101675/fb3ea2de-998f-4610-a199-cbbb1f26b36c)

## Business Value / Developer Experience
Better UX

## Acceptance Criteria
Possible to search for description in table view.

**Comment by Gustav-Eikaas** [comment]
https://github.dev/equinor/fusion-data-gateway/blob/fa55c0107f440e8e68a35c9d5c573364e3f0b534/src/CCApplications.Applications/HeatTraceApplication/Domain/HeatTraceFilter.cs#L32 

The _searchConfig defines which properties should be searchable. Looks like description is already defined?

**Comment by MagnusGjosund** [comment]
Yes it is. I will close this issue
