### ISSUE TITLE
🎁: SWCR - New filter "Reference value"

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#830]
## Expected outcome
User can filter on SWCR referenceValue

## Business Value / Developer Experience
Today users can filter on referenceType, but not referenceValue
( References is used to tag/label SWCR's )

This is a multifield value just like referenceType.
Value is available in FAM already joined in to the view. (Same table as referenceType)
![image](https://github.com/equinor/cc-components/assets/11732817/8989d379-3308-44a3-8fcd-9820b23afdd4)
referenceType = Attribute name: Code
referenceValue = Attribute name: Description

## Acceptance Criteria
- [ ] Can filter on referenceValue

**Comment by JoneUE** [comment]
This will not be prioritized now
