### ISSUE TITLE
✨: Pipetest Circuit Diagram

### ISSUE THREAD

**Issue by kjellhaaland** [equinor/cc-components#833]
## Expected outcome
Add support for pipetest to the Circuit Diagram. Currently the diagram only supports HT.
Similar view as the JC Circuit Diagram.

![image](https://github.com/equinor/cc-components/assets/17578087/74b10de9-ee51-475c-892a-27c13180314f)

The relation betweeen HT cables and Pipetest need to be added, as it is currently not part of the data returned from the API.

## Business Value / Developer Experience
Enables the user to se pipetests related to HeatTrace.

## Acceptance Criteria

- [x] All Pipetests related to all HT cables are shown in the Circuit Diagram.
- [ ] The currently selected Pipetest is highlighted in the diagram

**Comment by kjellhaaland** [comment]
The current API implementation (ElectricalConsumers), does not return pipetests as part of the "network tree". 
It uses the `/portal/{facility}/ele-net-consumer?tagNo={tagNo}` endpoint in STID to fetch the data.

How to get the Pipetest tags as part of the data returned from STID?

**Some suggestions to solutions**

1. Change the underlying view in the STID API, to include the pipetest tags in the response
2. Use the already implemented `EnrichWithFamTagsAsync` in the ElectricalConsumers API to enrich the data. This function gets tags from `Custom_ElectricalConsumersMCCR`. Can Pipetests in some way be included here?
3. Enrich the data from STID with data from FAM by using the Custom_PipetestV1 view, by querying for HT tags.

@atlewee any thoughts on this?

**Comment by atlewee** [comment]
@kjellhaaland 
Should be somehow picked up from this table in FAM:
( master mapping table between HT and PipeTest )
TagId is htCable id
![image](https://github.com/equinor/cc-components/assets/11732817/18262463-2825-4a53-9d9a-746ebd87938d)

**Comment by ken-mellem** [comment]
@kjellhaaland I guess this warrants a chat.
