### ISSUE TITLE
🎁: Add CPCL for checklists in HT

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#835]
## Expected outcome

There are also some C-tests(ELE19,3) in OGP that are CPCLs so we need to enable CPCL for the sidesheet. And then also add a column to show which are MCCRs and which are CPCLs

- [x] Remove filter on CPCL in View
- [x] Add column in HT sidesheet for Form Group

**Comment by aman-riaz** [comment]
Fixed in view - will be out in production on tuesday. 

@MagnusGjosund  can you add the column "FormularGroup" in sidesheet of HT?

**Comment by aman-riaz** [comment]
This is done, closing this issue.
