### ISSUE TITLE
🎁: Auto-width for columns in WorkOrder table component

### ISSUE THREAD

**Issue by kjellhaaland** [equinor/cc-components#851]
Implement auto-width for columns in the WorkOrder table component.
(Not sure if this exist in the table component out-of-the-box.

## Expected outcome
Automatically scaled column widths in the table, so that it does not take more space than necessary.

Would improve readability in the tables a lot, and avoid space-wasting like this:
![image(2)](https://github.com/equinor/cc-components/assets/17578087/dab620be-322a-46b9-a38f-67f6a8655383)

## Business Value / Developer Experience
Improves readability of the data in the table by not wasting already limited space on white space.

**Comment by kjellhaaland** [comment]
@EdwardBrunton, can this be moved to Done?

**Comment by EdwardBrunton** [comment]
@kjellhaaland I wasnt sure what the process was for closing issues, after it is merged should i just close it or does someone else test it first?
