### ISSUE TITLE
🎁: Remove Excel-Export from Grid Options when not availible

### ISSUE THREAD

**Issue by kjellhaaland** [equinor/cc-components#852]
## Expected outcome
Hiding the "Export to Excel" button from availible options when no excel export is configured for a given table.
The button should only be visible when such an export is defined.

## Business Value / Developer Experience
De-clutters the UI for users by removing the non-relevant button.
Prevents confusion and unnecessary questions about "Why it is not available".

## Acceptance Criteria
The "Export to Excel" grid option is invisible if it is not configured.

**Comment by ken-mellem** [comment]
@EdwardBrunton it appears this was not closed when the PR was merged..? Can you confirm - close the issue if correct.

**Comment by EdwardBrunton** [comment]
@ken-mellem seams like i forgot to close it
