### ISSUE TITLE
🎁: FAM data: Rewrite Custom_Scope_Tag 

### ISSUE THREAD

**Issue by aman-riaz** [equinor/cc-components#870]
Meeting with FAM regarding Scope_tag view. The current view is technical debt and is created in python. They suggested to rewrite the code to be more optimized and to follow the same workflow as the other views. 

I will look into this to find possible optimizations and will rewrite the code.

**Comment by MagnusGjosund** [comment]
I'm pretty sure RC is the only one that are using Custom_Scope_Tag

**Comment by JoneUE** [comment]
I think maybe Piping and Heattrace in JC uses it as well

**Comment by aman-riaz** [comment]
This is completed and in use now.
