### ISSUE TITLE
🐛: Workorder endpoint for Handover is slow

### ISSUE THREAD

**Issue by espenkalle** [equinor/cc-components#873]
Fetching workorders for handover sidesheet takes 10s 

Probably connected to the procosys fam data transfer. 

Investigate if there is a preprocess updated view that is being used / should be used.

**Comment by JoneUE** [comment]
@espenkalle Is this fixed? for me it takes about 2-3 seconds

**Comment by JoneUE** [comment]
Seem to be fixed
