### ISSUE TITLE
🐛: SWCR - Garden view fails 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#874]
## Description
Garden view fails.

{
    "title": "Server Error",
    "statusCode": 500,
    "detail": "Failed to compare two elements in the array.",
    "validationErrors": null
}

## Reproduce
Open the garden view in SWCR. This will crash :(

## Expected behavior
Garden works as expected

**Comment by JoneUE** [comment]
@MagnusGjosund Unable to replicate this. Is this still an issue?

**Comment by MagnusGjosund** [comment]
Seems like it's only failing in test, not prod

**Comment by JoneUE** [comment]
Closing this then
