### ISSUE TITLE
🐛: WO responsible is empty in sidesheet

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#881]
## Description

Grouping in garden also gives null values

![Image](https://github.com/equinor/cc-components/assets/73601851/e7b4d4d0-159b-448a-a434-ef3c685e4733)

**Comment by Gustav-Eikaas** [comment]
Did some digging and what is happening is that the filter is using ResponsibleCode and the sidesheet is using Responsible.
![image](https://github.com/equinor/cc-components/assets/89254170/42a684cc-5519-4f26-9c79-913618c1ace3)
I can switch so that the sidesheet also shows ResponsibleCode?

**Comment by Gustav-Eikaas** [comment]
It is for OGP atleast for all the ones I clicked through but for Castberg it has values

**Comment by kjellhaaland** [comment]
@JoneUE Any thoughts on this, should we use _responsibleCode_ instead of _responsible_ field?
PR fix is ready here: https://github.com/equinor/cc-components/pull/931

**Comment by JoneUE** [comment]
Ja, vare bruke code isteden for
