### ISSUE TITLE
🎁: WO Garden Grouping names

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#883]
## Expected outcome

- [x] Responsible -> WO Responsible
- [x] Milestone -> WO Milestone
- [x] Hours Readt For Execution At Site ( Should be removed and added to header in all groupings)
- [x] Discipline Code -> WO Discipline
- [x] Finalizing Workorders at Site -> WO Planned Completion
- [x] WO Planned Start
- [x] Workorder Production? What is this based on?
- [x] Comm RFCC

**Comment by EdwardBrunton** [comment]
Removal of "Hours Ready For Execution At Site" is related to https://github.com/equinor/fusion-data-gateway/issues/185
