### ISSUE TITLE
✨ Implement 3D 

### ISSUE THREAD

**Issue by kjellhaaland** [equinor/cc-components#887]
Finish the following list of actions needed to complete the 3D component.

- [x] Implement support for different environments (CI/CD) 
This is currently hard-coded
See widget/{widget}/config.ts for more details on how it is set up

- [x] Fix support for multiple facilities. 
Currently the first element in the list of facilities are taken

- [x] Widgets does not support the current implementation of CustomActions
If custom actions are needed, a new widget has to be created and the actions defined in the widget.

- [x] Add API endpoints for fetching which tags that are relevant for 3D.
This is straight-forward for WorkOrder and Punch, but other applications such as Handover, HeatTrace and Pipetest is more complex. The endpoint should return the tags that are relevant for 3D.

**Comment by kjellhaaland** [comment]
The development of the widget is almost done, but we are currently blocked to deploy to test by an issue in the fusion apps API.
Seems like the bundle size is to large to be uploaded.

@alftore is currently working on resolving it.

**Comment by ken-mellem** [comment]
As this is implemented differently - and an ADR suggests an different approach, what actions should we take on this @kjellhaaland?

**Comment by kjellhaaland** [comment]
The baseline 3D ModelViewer is now ready for test.
@JoneUE og @atlewee, can you verify that it is OK?

Not all work-orders have tags that are viewable in 3D. Use this for testing: 800469 (it should have some hits)

Link to test: 
https://webserver-fusion-project-portal-test.radix.equinor.com/apps/workorder/94dd5f4d-17f1-4312-bf75-ad75f4d9572c?tab=grid&item=ef6c01be-2097-baa3-e053-2710000a6dba

**Comment by kjellhaaland** [comment]
**For future reference:**

After a lot of back-and-forth with how to implement this, it was decided that we skip using widgets for this implementation.

This decision is documented in an ADR: https://github.com/equinor/lighthouse/blob/main/docs/decisions/004-modelviewer-bundling.md
