### ISSUE TITLE
🎁 Handover (SideSheet) - Add a tab for Notifications  (ProCoSys Notification object)

### ISSUE THREAD

**Issue by atlewee** [equinor/cc-components#894]
## Expected outcome
User can see notifications connected to a commPk

## Business Value / Developer Experience
Users already have this feature in legacy Fusion so it must also be added in the new handover app before sunsetting old legacy handover app.

## Acceptance Criteria
Notifications is shown as a tab in Commpk similar to how it is displayed in "Fusion handover-garden"

**Comment by ken-mellem** [comment]
Waiting for relevant data to be exported to FAM.

**Comment by JoneUE** [comment]
This is a dupliacte
