### ISSUE TITLE
✨: Loop improvements

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#897]
# Loop improvements

## Feedback from JC Loop testing team 

They like the new version of loop better than the old one. Some much needed columns were added. 
Some of the work they do cannot be done using the tool atm. They showed us an excel sheet they had made. This sheet is updated manually every 24hrs.
They are sourcing data from Fusion. After reviewing the Excel sheet we identified some key fields we should aim to include in our application

- [ ] LUN status. (Livening up notice)
- [ ] Energy source
- [ ] McPkg for Energy source
- [ ] Holding code A-G

LUN is a certificate on a loop tags mc pkg
Energy source is the tag that is powering the loop
Holding code is a calculated field on what is holding it back. E.g C for construction

**Comment by ken-mellem** [comment]
I want to raise the awareness of this.

**Comment by Gustav-Eikaas** [comment]
I agree but we need PO involvement in investigating the business aspect of this

**Comment by ken-mellem** [comment]
@JoneUE please evaluate. There were some really nice findings from Edward.

**Comment by JoneUE** [comment]
There is no easy way to set this up, Still not sure if it's possible to do the way PCS is set up now

**Comment by JoneUE** [comment]
Not possible
