### ISSUE TITLE
🖌️: Pipetest : Onboard the Pipetest app to production

### ISSUE THREAD

**Issue by kjellhaaland** [equinor/cc-components#913]
## Current state 
The Pipetest app is currently available in test for JCA.

## Desired state 
The Pipetest app should be availible in production for JCA and OGP? (Verify this)

## Acceptance Criteria

- [ ] App is working as expected
- [ ] PBI reports is working as expected

**Comment by kjellhaaland** [comment]
@JoneUE,

Two questions:
- Which projects should the Pipetest app be on-boarded for?
- Which projects should the HeatTracea app be on-boarded for?

@MagnusGjosund FYI

**Comment by JoneUE** [comment]
We can onboard them for all the 10 projects that we did for the rest of the CC apps

**Comment by kjellhaaland** [comment]
List of contexts to onboard: https://github.com/equinor/lighthouse/discussions/552

**Comment by kjellhaaland** [comment]
@JoneUE (@atlewee) FYI: Pipetest is now onboarded on the 10 new contexts/projects mentioned above

**Comment by kjellhaaland** [comment]
@JoneUE (@atlewee) FYI: Heat-Trace is now onboarded on the 10 new contexts/projects mentioned above

**Comment by kjellhaaland** [comment]
Closing this issue, as both the HeatTrace and Pipetest apps are onboarded on contexts in prod.
