### ISSUE TITLE
🐛: Mechanical Completion: WO sidesheet wrong URL

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#954]
## Description

When clikcing WO in sidesheet, you are sent to Mcpkg in PCS not to the WO

![Image](https://github.com/equinor/cc-components/assets/73601851/2cbf6fee-cb33-4138-8675-993739218789)

**Comment by atlewee** [comment]
Same issue in Project Portal

**Comment by atlewee** [comment]
handled by #1800
