### ISSUE TITLE
🎁: Workorder: Remove cutoff tab

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#988]
## Expected outcome
Remove the cutoff tab in Workorder sidesheet

![Image](https://github.com/equinor/cc-components/assets/73601851/fa7d175f-ebbc-4cd3-9aee-f1b089698aba)

**Comment by Gustav-Eikaas** [comment]
Why?

**Comment by JoneUE** [comment]
It is just loading really slow, and we don't see much use case for it. And if so then they should get the information they need i a better way in analytics
